PUSH =commands.PushCommand
DEFINE =commands.DefineCommand
+ =commands.AddCommand
- =commands.SubtractCommand
* =commands.MultiplyCommand
/ =commands.DivideCommand
POP =commands.PopCommand
SQRT =commands.SqrtCommand
PRINT = commands.PrintCommands